### ISSUE TITLE
Feature parsing logic from support2.csv to support_parsed.csv

### ISSUE THREAD

**Issue by abhishekmishra2505** [MGensheimer/nnet-survival#1]
I would like to get logic of framing support_parsed dataset from raw support2.csv file.
Basically i am curious to know about time and death columns in parsed files.

**Comment by MGensheimer** [comment]
Please check out the support_study_parse_data.R file, this shows how the data are parsed to create support_parsed.csv.
The original SUPPORT 2 trial dataset can be found at https://hbiostat.org/data/
Sorry for the delayed response, I need to fix my notifications!
