### ISSUE TITLE
Calibration plots

### ISSUE THREAD

**Issue by KaranMehta21** [MGensheimer/nnet-survival#2]
Hi, 

I'm trying to plots calibration curves with the deepsurv model. To show predicted risk from the model versus observed risk. Please can you advise me on how to do this? I have a trained deepsurv model

Thanks

**Comment by MGensheimer** [comment]
There are various kinds of calibration plots. One option would be:
Sort the patients into 10 bins according to DeepSurv's probability of the patient living for >1 year.
For each bin, plot a Kaplan-Meier curve that shows actual survival time for that group.
For each cure, label it with the range of DeepSurv-predicted 1-year survival. That way you can see if DeepSurv tended to over- or under-predict survival time.
I'd recommend taking a look at Frank Harrell's work for ways to assess calibration of survival models. Such as Regression Modeling Strategies book.
